---
title: "R Notebook"
output: html_notebook
---

Data frame
```{r}
head(mtcars)
tail(mtcars)

str(mtcars)

```

```{r}
name <- c("Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune")
type <- c("Terrestrial planet", "Terrestrial planet", "Terrestrial planet", 
          "Terrestrial planet", "Gas giant", "Gas giant", "Gas giant", "Gas giant")
diameter <- c(0.382, 0.949, 1, 0.532, 11.209, 9.449, 4.007, 3.883)
rotation <- c(58.64, -243.02, 1, 1.03, 0.41, 0.43, -0.72, 0.67)
rings <- c(FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE)
planets_df <- data.frame(name,type,diameter,rotation,rings)
planets_df

```

selectrion of data frame elements 
El simbolo de admiracion da el negado de una variable booleana
```{r}
planets_df[1,3]
planets_df[4,]
planets_df[1:5,]
planets_df[1:5, "rotation"]
planets_df[1:5,c("rotation","type")]
rings_vector <- planets_df$rings
rings_vector

planets_df[!rings_vector,]
subset(planets_df, subset = diameter < 1)

```
SORTING
```{r}
a <- c(100,10,1000)
order (a)
b <- a[order(a)]
b

positions <- order(planets_df$diameter)
positions
planets_df[positions,c("diameter","type")]
```

Listas


```{r}
my_vector <- 1:10
my_matrix <- matrix(1:9, ncol=3)
my_df <- planets_df[1:4,]
my_list <- list(my_vector,my_matrix,my_df)
my_list


```
creating a named list
```{r}
names(my_list)<- c("vector","matrix","data frame")
my_list
```
Selecting elements from a list 
```{r}
my_list[[2]][2,2]
my_list[[2]][2,]
my_list[[3]][2:3,1:2]
my_list[[3]][2:3,c("rotation","rings")]
```


