---
title: "R Notebook"
output: html_notebook
---
.
FUNCIONES

```{r}
Pow_two <- function (x, print_info= TRUE){
  y <- x^2
  if(print_info){
    print(paste(x,"to the power of two equals ",y))
  }
  return (y)
}

result <- Pow_two(3)
result # las variables dentro de la funcion no son globales
  
```
R passes arguments by value
```{r}
triple <- function(x){
  x <- 3*x
  x
}
a <- 5
triple(a)
a
```
```{r}
linkedin <- c(16,9,13,5,2,17,14)
interpret <- function(num_views){
  if(num_views >15){
    print("Youre Popular")
    return(num_views)
  }
  else{
    print("Try to be more visible")
    return(0)
  }
}
interpret(linkedin[1])

interpret_all <- function(views, return_sum=TRUE){
  count <- 0
  for(v in views){
    count <- count + interpret(v)
  }
  if(return_sum){
    return(count)
    
  }else{
    return(NULL)
  }
}
interpret_all(linkedin)
```
Load an R Package
```{r}
library(ggplot2)

qplot(mtcars$wt, mtcars$hp)
```
LAPPLY()
posiciones con doble corchete, referencia para una lista

```{r}
temp <- list(c(3,7,9,6,1), c(6,9,12,13,5), c(4,8,3,-1,-3), c(1,4,7,2,-2), c(5,7,9,4,2), c(-3,5,8,9,4), c(3,6,9,4,1))
select <- function(x){
  print( mean(x))
}
lapply(temp,min)

list <- lapply(temp,select)
list
for(t in temp){
  print(min(t))
}

```

lapply and anonymous functions

```{r}
(function(x){3*x})(9)
pioneers <- c("GAUSS:1777", "BAYES:1702","PASCAL:1623","PEARSON:1857")

split <- strsplit(pioneers, split=":")
split_low <- lapply(split,tolower)

split
split_low
names <- lapply(split_low, function(x){x[1]})
names

years <- lapply(split_low, function(x){x[2]})

years
```
use lapply with additional arguments
usar lapply con argumentos adicionales

```{r}
select_el <- function(x, index){
  x[index]
}
names <- lapply(split_low, select_el,1)

names

years <- lapply(split_low, select_el, 2)

years

```


```{r}

extremes <- function (x){
  c(min = min(x), max=max(x))
}

lapply(temp, extremes)
sapply(temp, extremes)


temp2 <- list (1,2,3,4,5)

func_temp2 <- function (x){

  x
}

lapply (temp2, func_temp2)
sapply (temp2, func_temp2)

```

Vapply

```{r}

basics <- function (x)
  
{
  c(min=max(x), mean=mean(x), max=max(x))
  
}

lapply(temp, basics)
sapply(temp, basics)
vapply(temp, basics,numeric(3))

temp3 <- c("Guatemala", "Salvador","Honduras", "Nicaragua")

unique_letters <- function (name){
  bane <- gsub(" ", "", name)
  letters <- strsplit(name, split="")[[1]]
  unique (letters)
}

lapply (temp3, unique_letters)
sapply (temp3, unique_letters)
vapply (temp3, unique_letters, nchar(7))

```



utilities

```{r}

errors <- c(1.9, -2.6, 4.0, -9.5, -3.4, 7.3)

print (sum(abs(round(errors))))

?round

linkedin
facebook

li_vec <- unlist(linkedin)
fb_vec <- unlist(facebook)

li_vec

fb_vec

social_vec <- append (li_vec, fb_vec)
social_vec

sort(social_vec, decreasing=TRUE)

```

GREP & GREPL

```{r}


emails <- c("john.doe@ivyleague.edu", "education@world.gov", "dalai.lama@peace.org","invalid.edu", "quant@bigdatacollege.edu", "cookie.monster@sesame.tv")


grepl(pattern="edu", emails)

hits<-grep (patter="edu", x=emails)

emails[hits]
```



