---
title: "R Notebook"
output: html_notebook
---
```{r}
3 == (2 + 1)
"intermediate" != "r"
TRUE != FALSE
"Rchitect" != "rchitect"

toupper ("rchitect")


```

Greater and less than
```{r}
-6 *5+2>=10+1

"raining"<= "table"

TRUE >= FALSE



```
Compare vectors and matrices

```{r}

linkedin <- c(16,9,13,5,2,17,14)
facebook <- c(17,7,5,16,8,13,14)

linkedin > 15
facebook <= 10

linkedin > facebook

views <- matrix(c(linkedin, facebook), nrow = 2, byrow = TRUE)
views

views ==13
views >= 14

```
Logic operators

```{r}

TRUE & TRUE
FALSE | TRUE

linkedin <=10 & facebook ==13
linkedin <=10
facebook ==13

linkedin <=10 | facebook ==13
views > 11 & views <= 14
```
The if statement

```{r}

medium <- "Facebook"
num_views <- 14

if (medium == "Linkedin"){
  print ("Showing Linkedin infomration")
}

if (medium == "Linkedin"){
  print ("Showing Linkedin infomration")
}else{
  print ("unknown medium")
}


if (num_views >15 ){
  print ("You are popular")
}else{
  print ("Try to be more visible!")
}


if (medium == "Linkedin"){
  print ("Showing Linkedin infomration")
}

if (medium == "Linkedin"){
  print ("Showing Linkedin infomration")
}else{
  print ("unknown medium")
}
```
customize further else if

```{r}

if (medium =="linkedin"){
  print ("Showing linkedin information")
} else if (medium == "facebook"){ 
  print ("Showing facebook information")
} else {
    print ("unknown medium ")
}


```
else if 2.0
```{r}
number <- 110

if (number <10){
  if (number < 5){
    result <- "Extra small"
  }
  else {
    result <- "small"
  }
}else if (number < 100){
  result <- "medium"
}else {
  result <- "large"
}
  
print (result)

```

Loops

```{r}

speed <- 64

while (speed > 30){
  print (paste("your speed is: ", speed))
  if (speed>=48){
    print ("Slow down bit time!")
    speed<- speed -11
  }else {
    print ("slow down!")
    speed <- speed -6
  }
    
}

speed
```

Break

```{r}
speed <- 88

while (speed > 30){
  print (paste("your speed is: ", speed))
  if (speed>=80){
  break
  }
  
  if(speed > 48){
    print ("Slow down big time!")
    speed <- speed -11
  }
  else {
    print ("slow down!")
    speed <- speed -6
  }
    
}

speed
```

For

```{r}

linkedin <- c(16,9,13,5,2,17,14)

for (l in linkedin){
  print (l)
}
  
for (i in 1:length(linkedin)){
  print (linkedin[i])
}


```

Loop over a list

```{r}

nyc <- list (pop=8405837, boroughs = c("Manhatan", "Bronx", "Brooklyn", "Queens", "Staten Island"), capital=FALSE)

for (n in nyc){
  print(n)
}

for (i in 1:length(nyc)){
  if (i==2){
    for (j in  1:length(nyc[[i]])){
      print (nyc[[i]][j])
    }
  }
  else{
    print (nyc[[i]])
  }
}

class(linkedin)

```


Loop over the matrix

```{r}

linkedin <- c(16,9,13,5,2,17,14)
facebook <- c(17,7,5,16,8,13,14)

views <- matrix(c(linkedin, facebook), nrow =2, byrow=TRUE)
views

for (row in 1:nrow(views)){
  for(col in 1:ncol(views)){
    print (paste("on row", row, "and column", col, "contains", views [row,col]))
    
  }
}

```

